modLoader = "javafml"
loaderVersion = "[1,)"
license = "GPL-3.0"

[[mods]]
modId = "cellulosesz"
version = "${version}"
displayName = "CellulosesZ"
description = "Server utility mod for Minecraft 26.1.2."

[[dependencies.cellulosesz]]
modId = "neoforge"
type = "required"
versionRange = "[${neoforge_version},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cellulosesz]]
modId = "minecraft"
type = "required"
versionRange = "[${minecraft_version}]"
ordering = "NONE"
side = "BOTH"
